#!/bin/sh

# requires
commands=("gisty" "percol" "w3m" "tmux" "z" "rbenv" "pyenv")

# check exists
for i in "${commands[@]}"
  do
    if which $i >/dev/null; then
      echo `which $i` "is ok."
    fi
  done
